config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/contact'
  get 'static_pages/about'
  devise_for :users
  get '/tasks/status_update'
  resources :tasks

  get '/tasks/pickup_conf'

  post 'twilio/voice' => 'twilio#voice'

  resources :users

  root 'users#show'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  belongs_to :user
end

app/models/postmates.rb
module Postmates

  class Client
    include HTTParty

    KEY  = ENV['POSTMATES_API_KEY']
    USER = ENV['POSTMATES_CUSTOMER_ID']
    HOST = ENV['POSTMATES_HOST']
    PATH = "/v1/customers/#{USER}"


# API Notes:
# Request a Delivery quote
# POST /v1/customers/:customer_id/delivery_quotes

# Create a Delivery
# POST /v1/customers/:customer_id/deliveries

# Poll your newly created delivery to follow the status of your delivery
# GET /v1/customers/:customer_id/deliveries/:delivery_id

    def initialize
    end

    def create_delivery_quote(dropoff_pickup_hash)
      @quote_response ||= post('/delivery_quotes', dropoff_pickup_hash)  
    end


    def create_delivery(delivery_hash)
      @delivery_response ||= post('/deliveries', delivery_hash)  
    end

    def delivery_status(delivery_id)
      get("deliveries/#{delivery_id}")
      #@del_status ||= get("deliveries/#{delivery_id}") #not getting updated status with this assignment
    end


    private

    def post(end_point, params={})
      url = "#{HOST}#{PATH}#{end_point}"
      options = { basic_auth: {username: KEY},
                  body:       params
                }
      HTTParty.post(url, options)
    end

    def get(end_point, params={})
      url = "#{HOST}#{PATH}/#{end_point}"
      options = { basic_auth: {username: KEY},
                  body:       params
                }

      HTTParty.get(url, options) 
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  has_many :bikes
  has_many :addresses
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:about, :contact]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session # Added to prevent rails form secuity

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :phone, :email, :password, :password_confirmation) }
  end
end

app/controllers/concerns/webhookable.rb
module Webhookable
extend ActiveSupport::Concern

  def set_header
          response.headers["Content-Type"] = "text/xml"
  end

  def render_twiml(response)
          render text: response.text
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
      @user = User.new
  end

  def create
      puts "*****************"
      puts "we are in create session"
    @user = User.where(email: params[:email]).first
    binding.pry
    if @user && @user.authenticate(params[:users][:password_digest])
      session[:id] = @user.id
      puts "*****************"
      redirect_to "user_path"
    else
      @errors="your login credentials failed"
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

end

app/controllers/tasks_controller.rb
require 'httparty'
require 'faker'

class TasksController < ApplicationController

  skip_before_filter  :verify_authenticity_token  # Added this to prevent CSRF errors

  def index
  end

  def new
    p "tasks#new"
    @address = Address.new
    @bike = current_user.bikes.first
  end


  def create
    @task = Task.new(user_id:         current_user.id,
                     pickup_address:  "33 Montclair Terrace, San Francisco, CA 94109",
                     dropoff_address: "#{params[:street]},#{params[:city]}, #{params[:state]}, #{params[:zip_code]}",
                     status:          "initial" )
    if @task
      @task.save!
    end

    api = Postmates::Client.new

    #Get a Quote
    quote_response = api.create_delivery_quote( { dropoff_address: @task.dropoff_address, pickup_address: @task.pickup_address } )
    @task.quote_id = quote_response["id"]

    #Create a Delivery
    @user = User.find(current_user.id)
    @bike = @user.bikes.first

    pickup = "00:00:00"
    pickup_complete = "00:00:01"
    pickup_dropoff = "00:00:05"
    pickup_delivered = "00:00:45"

    delivery_hash = {
      manifest:             "#{@bike.color} #{@bike.make}",
      pickup_name:          "Bike Ready, Inc.",
      pickup_address:       @task.pickup_address,
      pickup_phone_number:  "415-555-1212",
      pickup_notes:         "Fragile",
      dropoff_name:         current_user.first_name,
      dropoff_address:      @task.dropoff_address,
      dropoff_phone_number: current_user.phone,
      quote_id:             @task.quote_id,
      robo_pickup:          pickup,
      robo_pickup_complete: pickup_complete,
      robo_dropoff:         pickup_dropoff,
      robo_delivered:       pickup_delivered
    }


    delivery_response = api.create_delivery(delivery_hash)

    @task.delivery_id = delivery_response["id"]
    @task.dropoff_lat_lng = JSON.generate(delivery_response["dropoff"]["location"])
    @task.pickup_lat_lng = JSON.generate(delivery_response["pickup"]["location"])
    @task.status = delivery_response["status"]

    @task.save!
    @bike.status = @task.status
    @bike.save!

    redirect_to '/'
  end

  def status_update
    @bike = current_user.bikes.first

    api = Postmates::Client.new

    if( @bike && @bike.status != "storage" &&  @bike.status != "delivered")
      @task = Task.where(user_id: current_user.id).last

      del_status_response = api.delivery_status(@task.delivery_id)
      if del_status_response["status"] != @task.status
        @task.status = del_status_response["status"]
        @bike.status = @task.status
        @task.save!
        @bike.save!
      end

      account_sid  = ENV['TWILIO_ACCOUNTSID_PROD']
      auth_token = ENV['TWILIO_AUTH_TOKEN_PROD']

        p "********************"
        p @task.status
        p "********************"
      # set up a client to talk to the Twilio REST API
      if (@task.status == "delivered")
        begin
          @client = Twilio::REST::Client.new(account_sid, auth_token)
          @message = @client.account.messages.create({:to => "+1#{current_user.phone}", :from => "+16502354317", :body => Faker::Hacker.say_something_smart})
        rescue Twilio::REST::RequestError => e  
          puts e.emessage
        end
      end

      render :json => {status: @task.status}
    else
      render :json => {:message => "error"}
    end
  end

  def pickup_conf
    p "tasks#pickup_conf"
  end

  private

  def task_params
    params.require(:task).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = current_user
    @bike = current_user.bikes.first

      
    #get bike status
    if (@bike && @bike.status != 'storage' && @bike.status != 'delivered')
      api = Postmates::Client.new
      @task = Task.where(user_id: current_user.id).last
      del_status_response = api.delivery_status(@task.delivery_id)
      @bike.status = del_status_response["status"]
      @bike.save!
      
      task_dropoff_lat_lng = JSON.parse(@task.dropoff_lat_lng)
      @task_dropoff_lat = task_dropoff_lat_lng["lat"]
      @task_dropoff_lng = task_dropoff_lat_lng["lng"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikeready</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOG_KEY'] %>">
  </script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Bike Ready</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
               <% if @bike %>
                  <li>
                    <%= link_to 'Deliver Bike', new_task_path %>
                      <span class="sr-only">(current)</span>
                  </li>
               <%end%>
              <li><%= link_to 'About', static_pages_about_path %></li>
              <li><%= link_to 'Contact Us', static_pages_contact_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
             <li>
               <% if user_signed_in? %>
                 <li>
                   <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                 </li>
                 <li><%= image_tag(current_user.gravatar_url({size: 45}), class: "gravitar") %></li>
                 <% else %>
                   <%= link_to('Login', new_user_session_path)  %>
               <% end %>
            </li>
           </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

  <%= yield %>

  </div> <!-- /container -->
</body>
</html>

app/views/static_pages/about.html.erb
<div class="jumbotron">
<h1>About Us</h1>
<p>BikeReady is evolving the way the world moves. By seamlessly connecting bikers to their bikes through our apps, we make cities more accessible, opening up more possibilities for bikers and more business for the community. BikeReady's rapidly expanding global presence continues to bring people and their cities closer.</p>
</div>

app/views/static_pages/contact.html.erb
<div class="jumbotron">
  <h1>Contact Us</h1>
  <p>We love to get feedback from our users!</p>
  <ul class="field">
    <li>Calvin Settachatgul: calvin.settachatgul@gmail.com</li>
    <li>Derek Tang: derekztang@gmail.com</li>
    <li>Hugh Sutton-Gee: @thereal_hugh</li>
    <li>Joyce De La Torre: joycedelatorre87@gmail.com</li>
  </ul><br>
  <img class="height width" src="/images/bikeready.jpg" alt="">
</div>

app/views/tasks/new.html.erb
<!-- bootstrap -->

<div class="jumbotron">
  <h2>Where would you like to have your bike delivered?</h2>

  <div class="">
    <h3 class="manage_bike">Enter a delivery address:</h3>
    <form action="/tasks" method="post">
      <input type="text" name="street" placeholder="street">
      <input type="text" name="city" placeholder="city"><br>
      <input type="text" name="state" placeholder="state">
      <input type="text" name="zip_code" placeholder="zip"><br><br>
      <input type="submit" value="submit">
    </form>
  </div>
</div>

app/views/tasks/old_new_task.html.erb
<h1>Where would you like to have your Bike delivered:</h1>

<h3>Enter an delivery address:</h3>
<%= form_for :address do |f| %>
  <%= f.label :Street %>
  <%= f.text_field :street %>
  <%= f.label :City %>
  <%= f.text_field :city %>
  <%= f.label :State %>
  <%= f.text_field :state %>
  <%= f.label :Zipcode %>
  <%= f.text_field :zip_code %>
  <%= f.submit %>
<% end %>

app/views/tasks/pickup_conf.html.erb
pickup_conf.html.erb

app/views/users/previous_show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">
          Toggle navigation
        </span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        Bike Ready
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% if @bike %>
          <li class="active">
            <%= link_to 'Deliver Bike', new_task_path %>
              <span class="sr-only">(current)</span>
          </li>
          <li>
            <%= link_to 'Pick-up Bike', tasks_pickup_conf_path %>
          </li>
        <%end%>


        <% if @bike.status == 'pickup' || @bike.status =='pending'  %>
          <li>
            <%= link_to 'Cancel Request', tasks_pickup_conf_path %>
          </li>
        <%end%>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        </li>
        <% else %>
          <%= link_to('Login', new_user_session_path)  %>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>








<!-- below this is the information of the user and the bike status -->

<div class="body-container">
  <div class="title">
    <div class="banner">
      Manage your bike

    </div>

  </div>

  <div class="info">
    <img class="avatar" src="http://www.sessionlogs.com/media/icons/defaultIcon.png">

    <div class="user_name">
      <h3>You are signed in:
        <%= current_user.first_name %>
      </h3>
    </div>

    <% if @bike %>
      <div id="bike_status" class="div-bg">
        <h3>
          Bike Status: &nbsp;&nbsp;&nbsp; <%= @bike.status %>
        </h3>
      </div>
    <% end %>
    <div class="col-md-6" id="map-canvas">
      </div>  <!-- div for map -->
  </div>


</div> <!-- end of body container -->

app/views/users/show.html.erb
      <!-- Static navbar -->


      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1 class="manage_bike">Welcome <%= current_user.first_name %>! </h1>
        <p class="manage_bike">Get your bike delivered anywhere inside San Francisco, CA.  <% if @bike %>
          <div id="bike_status" class="div-bg">
            <p>Bike Status: &nbsp;&nbsp;&nbsp; <span class="bike-current-status"><%= @bike.status %></span><p>
          </div>
          <% end %>
        </p>
      </div>

      <div class="col-md-6" id="map-canvas"></div>  <!-- div for map -->

    <div id="footer">
      <div class="container">
        <p class="muted credit">BikeReady, &copy; 2015</p>
      </div>
    </div>

<script id="lat"><%= @task_dropoff_lat %></script>
<script id="lng"><%= @task_dropoff_lng %></script>
<%= javascript_include_tag "tasks" %>
<%= javascript_include_tag "maps" %>